name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      if: contains(github.event.head_commit.message, '.')
    - name: Sign-in to Docker
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      if: contains(github.event.head_commit.message, '.')
    - name: Build
      run: |
        tag=${{ github.event.head_commit.message }}
        docker build -t docker.pkg.github.com/cerberus/chrome-node-java:$tag .
        docker push docker.pkg.github.com/cerberus/chrome-node-java/image:$tag
      if: contains(github.event.head_commit.message, '.')
